GRANT SELECT,UPDATE,INSERT on &1.cent_log1 to &2;

GRANT EXECUTE on &1.LOG_DOPISZ_ZRODLO to &2;
GRANT EXECUTE on &1.ZAPISZ_LOG to &2;
GRANT EXECUTE on &1.ZAPISZ_LOGOWANIE to &2;
GRANT EXECUTE on &1.POBIERZ_NR_ODDZ to &2;
GRANT EXECUTE on &1.UZYTKOWNIK to &2;
GRANT EXECUTE on &1.ZNACZNIK_TO_IDENT to &2;

exit;