GRANT SELECT,UPDATE,INSERT,DELETE on &1.SPISS to &2;


GRANT EXECUTE on &1.ZAPISZ_ERR to &2;
GRANT EXECUTE on &1.ZAPISZ_LOG to &2;
GRANT EXECUTE on &1.ZNACZNIK_TO_IDENT to &2;
GRANT EXECUTE on &1.PKG_WH1 to &2;

exit;